### PR TITLE
Add Russian language

### PR DESCRIPTION
**Pull request by BullFFm**

### CODE REVIEW

**Comment by edgarchinchilla** [comment]
Hi @BullFFm 

Please update your branch with the latest version of the script and I will include your language changes!

**Comment by BullFFm** [comment]
Hi @edgarchinchilla

Updated.

**Review by edgarchinchilla — CHANGES_REQUESTED** [review]
Hi @BullFFm 

Please rebase your script again based on the latest version and I will merge your changes!

When re-base please update the version number of the script to 9.5.2 and the date to the date of the day!

**Comment by BullFFm** [comment]
Hi @edgarchinchilla

Updated.

**Pull request merged**
